# This is a basic workflow to help you get started with Actions

name: commit

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      commit-msg:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export-unmanaged:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: ScriptPatternsDemo
          solution-output-file: ScriptPatternsDemo.zip
          managed: false
          run-asynchronously: true
      - uses: actions/upload-artifact@v2
        with:
          name: unmanaged-solution
          path: ScriptPatternsDemo.zip
  export-managed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: ScriptPatternsDemo
          solution-output-file: ScriptPatternsDemo_managed.zip
          managed: true
          run-asynchronously: true
      - uses: actions/upload-artifact@v2
        with:
          name: managed-solution
          path: ScriptPatternsDemo_managed.zip
  unpack-commit:
    runs-on: ubuntu-latest
    needs: 
      - export-unmanaged
      - export-managed
    # Checkout the soultion(s) from the temp path
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with: 
          name: unmanaged-solution
          path: ${{ runner.temp }}
      - uses: actions/download-artifact@v2
        with: 
          name: managed-solution
          path: ${{ runner.temp }}
      # Unpack the Soultion(s)
      - uses: microsoft/powerplatform-actions/unpack-solution@v0
        with: 
          solution-file: ${{ runner.temp }}/ScriptPatternsDemo.zip
          solution-folder: solution
          solution-type: Both
      - uses: EndBug/add-and-commit@v7
      # TODO
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onevent_nametypes
        with: 
          message: ${{ github.event.inputs.commit-msg }}
          # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
